[project]
name = "geolocations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "geoalchemy2[shapely]>=0.20.0",
    "httpx2>=2.13.0",
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]
