"""added unique constraint to cities table

Revision ID: 2a9c38de0b52
Revises: fee74b65e8b8
Create Date: 2026-09-28 22:27:13.710960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9c38de0b52'
down_revision: Union[str, None] = 'fee74b65e8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_state_id_city_name', 'cities', ['state_id', 'name'], schema='locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_state_id_city_name', 'cities', schema='locations', type_='unique')
    # ### end Alembic commands ###
