"""added state, city and county tables within a locations schema

Revision ID: c7dd512e7dd1
Revises:
Create Date: 2026-09-23 19:56:23.895704

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7dd512e7dd1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counties",
        sa.Column("serial_id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "modified_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("serial_id"),
        sa.UniqueConstraint("id"),
        schema="locations",
    )
    op.create_table(
        "states",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("abbreviation", sa.String(length=2), nullable=False),
        sa.Column("tigerweb_number", sa.String(), nullable=False),
        sa.Column(
            "geo_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("serial_id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "modified_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("serial_id"),
        sa.UniqueConstraint("abbreviation", name="uq_states_abbreviation"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name", name="uq_states_name"),
        schema="locations",
    )
    # op.create_index(
    #     "idx_states_geo_location",
    #     "states",
    #     ["geo_location"],
    #     unique=False,
    #     schema="locations",
    #     postgresql_using="gist",
    # )
    op.create_table(
        "cities",
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tigerweb_number", sa.String(), nullable=False),
        sa.Column(
            "geo_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("serial_id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "modified_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["locations.states.id"],
        ),
        sa.PrimaryKeyConstraint("serial_id"),
        sa.UniqueConstraint("id"),
        schema="locations",
    )
    # op.create_index(
    #     "idx_cities_geo_location",
    #     "cities",
    #     ["geo_location"],
    #     unique=False,
    #     schema="locations",
    #     postgresql_using="gist",
    # )
    op.create_table(
        "county_cities",
        sa.Column("county_id", sa.UUID(), nullable=False),
        sa.Column("city_id", sa.UUID(), nullable=False),
        sa.Column("serial_id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "modified_by",
            sa.String(),
            server_default=sa.text("CURRENT_USER::regrole"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["locations.cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["locations.states.id"],
        ),
        sa.PrimaryKeyConstraint("serial_id"),
        sa.UniqueConstraint("county_id", "city_id", name="uq_county_city"),
        sa.UniqueConstraint("id"),
        schema="locations",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("county_cities", schema="locations")
    op.drop_index(
        "idx_cities_geo_location",
        table_name="cities",
        schema="locations",
        postgresql_using="gist",
    )
    op.drop_table("cities", schema="locations")
    op.drop_index(
        "idx_states_geo_location",
        table_name="states",
        schema="locations",
        postgresql_using="gist",
    )
    op.drop_table("states", schema="locations")
    op.drop_table("counties", schema="locations")
    # ### end Alembic commands ###
